formatter: "md"

content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Usage

  ```hcl
  module "" {
    source = "git@github.com:nop-systems/tf-modules.git//<module-path>?ref=<tag>"
    {{ range .Module.Inputs }}{{if .Required }}
    /* {{ .Description }} (required) */
    {{ .Name }} = 
    {{- end }}{{ end }}

    {{ range .Module.Inputs }}{{if not .Required }}
    /* {{ .Description }} (optional) */
    # {{ .Name }} = {{ .Default.Raw }}
    {{- end }}{{ end }}
  }

  module "" {
    source = "git@github.com:nop-systems/tf-modules.git//?ref="
    {{ range .Module.Inputs }}{{if .Required }}
    {{ .Name }} = 
    {{- end }}{{ end }}
  }
  ```
