# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.7.4"
  required_providers {
    vault = {
      source  = "hashicorp/vault"
      version = ">=4.3.0"
    }
  }
}
